### ISSUE TITLE
Cronitor fails to start on Docker desktop on Mac m1

### ISSUE THREAD

**Issue by USSliberty** [cronitorio/cronitor-kubernetes#18]
Hello, I tried to install the helm chart of Cronitor following the docs, however the POD keeps restarting due this error:

``` 
time="2022-10-20T14:57:13Z" level=info msg="Enabling Sentry instrumentation..."
time="2022-10-20T14:57:13Z" level=info msg="no kubeconfig provided, defaulting to in-cluster..."
Error: the server could not find the requested resource
Usage:
  cronitor-kubernetes agent [flags]

Flags:
      --dryrun             Dry run, do not actually send updates to Cronitor
  -h, --help               help for agent
      --namespace string   Scope agent collection to only a single Kubernetes namespace
      --ship-logs          Collect and archive the logs from each CronJob run upon completion or failure

Global Flags:
      --apikey string       Cronitor.io API key
      --kubeconfig string   path to a kubeconfig to use
      --log-level string    Minimum log level to print for the agent (TRACE, DEBUG, INFO, WARN, ERROR)
```

**Comment by jdotjdot** [comment]
Thanks for sending this in.  We haven't seen this particular issue before and I can't reproduce, so it may take a few questions back and forth to get to the bottom of it.

* What version of the Helm chart are you using? 
* What version of Kubernetes are you using?
* Are you deploying it cluster-wide, or in a single namespace? (e.g., in the chart values, is `rbac.clusterScope` "cluster" or "namespace"?)
* Would you be able to set `config.yourEmail` and  `config.sentryEnabled` to help us debug?

**Comment by jdotjdot** [comment]
I would also note, the Cronitor agent has not been tested extensively with Docker Desktop -- Docker makes some compromises to get Kubernetes running in a non-standard environment. For local usage, we use [kind](https://kind.sigs.k8s.io/). Have you tried with kind or deploying the Cronitor agent into your production environment?

**Comment by jdotjdot** [comment]
Yes -- you installed it correctly, when I was asking about namespace vs cluster, it meant the scope of what Cronitor was monitoring, not the installation itself. Installs have to happen in one namespace by virtue of how Kubernetes works.

Let us know how it goes with `kind`!

**Comment by jdotjdot** [comment]
I think the issue here is actually with the version of Kubernetes you're using, we need to update the agent. I'll follow up on this.

**Comment by jdotjdot** [comment]
Great! It looks like the agent doesn't work in 1.25 yet, but for 1.23 you should be good if that's what you use in production!
