### ISSUE TITLE
Add annotation for group assignment

### ISSUE THREAD

**Issue by mowings** [cronitorio/cronitor-kubernetes#24]
Using groups is currently pretty awkward for k8s job deployments. We like them, but the assigning the group is a manual process that has to be done post job creation. 

I'd propose adding a new annotation so that the cronitor-agent can automatically assign the monitor for a job to a particular group:

    k8s.cronitor.io/cronitor-group: "foo-jobs"

This would allow us to specify the monitor group at deployment time, which would simplify our lives quite a bit

**Comment by aflanagan** [comment]
@mowings This is available in the 0.4.5 release along with a `cronitor-notify` annotation as well!
