### ISSUE TITLE
Customize the "Complete" Signal Timing 

### ISSUE THREAD

**Issue by KqLLL** [cronitorio/cronitor-kubernetes#38]
## Request for New Feature：

We need to customize the timing of sending the "complete" signal because we will combine the queue for asynchronous task processing. Therefore, the completion of a cronjob does not signify the end of the entire task execution. The "complete" ping should be sent by the program after all tasks in the queue have been fully processed.
* Disable the cronitor telemetry ping from cronitor-kubernetes.

## Recommend

Is it possible to turn off cronitor-kubernetes telemetry pings and send telemetry entirely by the users themselves.

Can we define a new annotation similar to "k8s.cronitor.io/disable-complete"? If this is set to true, the sending of the complete signal should be ignored.

**Comment by KqLLL** [comment]
Is it possible to turn off cronitor-kubernetes telemetry pings and send telemetry entirely by the users themselves.

**Comment by aflanagan** [comment]
Hi @KqLLL,

It's not possible to just disable the complete ping, and I'm not sure we want to add this as an option in the agent itself. However, you can use the `k8s.cronitor.io/exclude` annotation to disabled the automatic monitoring for this job(s), and you could then implement sending the telemetry events yourself within the jobs themselves. This is easy to do using any http client - https://cronitor.io/docs/telemetry-api
